<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC8dfW3i\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC8dfW3i/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerC8dfW3i.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerC8dfW3i\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerC8dfW3i\App_KernelProdContainer([
    'container.build_hash' => 'C8dfW3i',
    'container.build_id' => 'e16dbef5',
    'container.build_time' => 1765308882,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC8dfW3i');
