<?php

namespace Container1vUcB4F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikJwtAuthentication_GenerateTokenCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'lexik_jwt_authentication.generate_token_command' shared service.
     *
     * @return \Lexik\Bundle\JWTAuthenticationBundle\Command\GenerateTokenCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/lexik/jwt-authentication-bundle/Command/GenerateTokenCommand.php';

        $container->services['lexik_jwt_authentication.generate_token_command'] = $instance = new \Lexik\Bundle\JWTAuthenticationBundle\Command\GenerateTokenCommand(($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.user.provider.concrete.usuario_provider'] ?? $container->load('getSecurity_User_Provider_Concrete_UsuarioProviderService'));
            yield 1 => ($container->privates['security.user.provider.concrete.entrenador_provider'] ?? $container->load('getSecurity_User_Provider_Concrete_EntrenadorProviderService'));
            yield 2 => ($container->privates['security.user.provider.concrete.chain_provider'] ?? $container->load('getSecurity_User_Provider_Concrete_ChainProviderService'));
        }, 3));

        $instance->setName('lexik:jwt:generate-token');
        $instance->setDescription('Generates a JWT token for a given user.');

        return $instance;
    }
}
