<?php

namespace ContainerPAnpPIT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscripcionControlleractivarPremiumService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z0lwIhD.App\Controller\SubscripcionController::activarPremium()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z0lwIhD.App\\Controller\\SubscripcionController::activarPremium()'] = ($container->privates['.service_locator.z0lwIhD'] ?? $container->load('get_ServiceLocator_Z0lwIhDService'))->withContext('App\\Controller\\SubscripcionController::activarPremium()', $container);
    }
}
