<?php

namespace ContainerCPBQlaO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDietaControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DietaController' shared autowired service.
     *
     * @return \App\Controller\DietaController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DietaController'] = $instance = new \App\Controller\DietaController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\DietaController', $container));

        return $instance;
    }
}
