<?php

namespace ContainerCPBQlaO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDietasPublicasControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DietasPublicasController' shared autowired service.
     *
     * @return \App\Controller\DietasPublicasController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DietasPublicasController'] = $instance = new \App\Controller\DietasPublicasController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\DietasPublicasController', $container));

        return $instance;
    }
}
