<?php

namespace ContainerCPBQlaO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrenadorRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EntrenadorRepository' shared autowired service.
     *
     * @return \App\Repository\EntrenadorRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EntrenadorRepository'] = new \App\Repository\EntrenadorRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
