<?php

namespace ContainerCPBQlaO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrenadorLoginSuccessHandler_InnerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\EntrenadorLoginSuccessHandler.inner' shared autowired service.
     *
     * @return \App\Security\UsuarioLoginSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Security\\UsuarioLoginSuccessHandler.inner'] ?? $container->load('getUsuarioLoginSuccessHandler_InnerService'));

        if (isset($container->privates['App\\Security\\EntrenadorLoginSuccessHandler.inner'])) {
            return $container->privates['App\\Security\\EntrenadorLoginSuccessHandler.inner'];
        }

        return $container->privates['App\\Security\\EntrenadorLoginSuccessHandler.inner'] = new \App\Security\UsuarioLoginSuccessHandler($a, ($container->privates['App\\Repository\\UsuarioRepository'] ?? $container->load('getUsuarioRepositoryService')));
    }
}
