<?php

namespace ContainerCPBQlaO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMisDietasControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MisDietasController' shared autowired service.
     *
     * @return \App\Controller\MisDietasController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MisDietasController'] = $instance = new \App\Controller\MisDietasController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\MisDietasController', $container));

        return $instance;
    }
}
