<?php

namespace ContainerCPBQlaO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PlatoRepository' shared autowired service.
     *
     * @return \App\Repository\PlatoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PlatoRepository'] = new \App\Repository\PlatoRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
