<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDIBQ3BK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDIBQ3BK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDIBQ3BK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDIBQ3BK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDIBQ3BK\App_KernelDevDebugContainer([
    'container.build_hash' => 'DIBQ3BK',
    'container.build_id' => '4dd59c60',
    'container.build_time' => 1765106972,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDIBQ3BK');
