<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKLwWvNV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKLwWvNV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKLwWvNV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKLwWvNV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKLwWvNV\App_KernelDevDebugContainer([
    'container.build_hash' => 'KLwWvNV',
    'container.build_id' => '6d0bf3db',
    'container.build_time' => 1765111044,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKLwWvNV');
