<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerArzVnn8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerArzVnn8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerArzVnn8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerArzVnn8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerArzVnn8\App_KernelDevDebugContainer([
    'container.build_hash' => 'ArzVnn8',
    'container.build_id' => '5c4e1c05',
    'container.build_time' => 1765075897,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerArzVnn8');
