<?php

namespace ContainerArzVnn8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrenadorControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EntrenadorController' shared autowired service.
     *
     * @return \App\Controller\EntrenadorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EntrenadorController.php';
        include_once \dirname(__DIR__, 4).'/src/Security/RoleChecker.php';

        $container->services['App\\Controller\\EntrenadorController'] = $instance = new \App\Controller\EntrenadorController(($container->privates['App\\Repository\\EntrenadorRepository'] ?? $container->load('getEntrenadorRepositoryService')), ($container->privates['App\\Repository\\UsuarioRepository'] ?? $container->load('getUsuarioRepositoryService')), ($container->privates['App\\Repository\\EntrenamientoRepository'] ?? $container->load('getEntrenamientoRepositoryService')), ($container->privates['App\\Repository\\DietaRepository'] ?? $container->load('getDietaRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Security\\RoleChecker'] ??= new \App\Security\RoleChecker()));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\EntrenadorController', $container));

        return $instance;
    }
}
