<?php

namespace ContainerArzVnn8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrenadorLoginSuccessHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Security\EntrenadorLoginSuccessHandler' shared autowired service.
     *
     * @return \App\Security\EntrenadorLoginSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticationSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/EntrenadorLoginSuccessHandler.php';

        return $container->services['App\\Security\\EntrenadorLoginSuccessHandler'] = new \App\Security\EntrenadorLoginSuccessHandler(($container->privates['App\\Security\\EntrenadorLoginSuccessHandler.inner'] ?? $container->load('getEntrenadorLoginSuccessHandler_InnerService')), ($container->privates['App\\Repository\\EntrenadorRepository'] ?? $container->load('getEntrenadorRepositoryService')));
    }
}
