<?php

namespace ContainerArzVnn8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioLoginSuccessHandler_InnerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\UsuarioLoginSuccessHandler.inner' shared service.
     *
     * @return \Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Authentication\AuthenticationSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticationSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/lexik/jwt-authentication-bundle/Security/Http/Authentication/AuthenticationSuccessHandler.php';

        $a = ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService'));

        if (isset($container->privates['App\\Security\\UsuarioLoginSuccessHandler.inner'])) {
            return $container->privates['App\\Security\\UsuarioLoginSuccessHandler.inner'];
        }

        return $container->privates['App\\Security\\UsuarioLoginSuccessHandler.inner'] = new \Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Authentication\AuthenticationSuccessHandler($a, ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), [], true);
    }
}
