# Imagen base de MySQL
FROM mysql:8.0

# Variables de entorno para la configuración inicial
ENV MYSQL_ROOT_PASSWORD=josefa
ENV MYSQL_DATABASE=ultimatefitness_db
ENV MYSQL_USER=jose
ENV MYSQL_PASSWORD=josefa

# Expone el puerto de MySQL
EXPOSE 3306