<?php

namespace ContainerC8dfW3i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiaEntrenamientoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DiaEntrenamientoRepository' shared autowired service.
     *
     * @return \App\Repository\DiaEntrenamientoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DiaEntrenamientoRepository'] = new \App\Repository\DiaEntrenamientoRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
