<?php

namespace ContainerC8dfW3i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEjercicioRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EjercicioRepository' shared autowired service.
     *
     * @return \App\Repository\EjercicioRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EjercicioRepository'] = new \App\Repository\EjercicioRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
