<?php

namespace ContainerC8dfW3i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrenadorAuthControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\EntrenadorAuthController' shared autowired service.
     *
     * @return \App\Controller\EntrenadorAuthController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EntrenadorAuthController'] = $instance = new \App\Controller\EntrenadorAuthController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\EntrenadorAuthController', $container));

        return $instance;
    }
}
