<?php

namespace ContainerC8dfW3i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMisClientesControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MisClientesController' shared autowired service.
     *
     * @return \App\Controller\MisClientesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MisClientesController'] = $instance = new \App\Controller\MisClientesController(($container->privates['App\\Repository\\UsuarioRepository'] ?? $container->load('getUsuarioRepositoryService')), ($container->privates['App\\Repository\\SuscripcionRepository'] ?? $container->load('getSuscripcionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\MisClientesController', $container));

        return $instance;
    }
}
