<?php

namespace ContainerC8dfW3i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistroControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\RegistroController' shared autowired service.
     *
     * @return \App\Controller\RegistroController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\RegistroController'] = $instance = new \App\Controller\RegistroController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['App\\Repository\\UsuarioRepository'] ?? $container->load('getUsuarioRepositoryService')), ($container->privates['App\\Repository\\EntrenadorRepository'] ?? $container->load('getEntrenadorRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\RegistroController', $container));

        return $instance;
    }
}
