<?php

namespace ContainerC8dfW3i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Authenticator_LoginTrainerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.authenticator.login_trainer' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.authenticator.json_login.login_trainer'] ?? $container->load('getSecurity_Authenticator_JsonLogin_LoginTrainerService'));

        if (isset($container->privates['security.firewall.authenticator.login_trainer'])) {
            return $container->privates['security.firewall.authenticator.login_trainer'];
        }

        return $container->privates['security.firewall.authenticator.login_trainer'] = new \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener(new \Symfony\Component\Security\Http\Authentication\AuthenticatorManager([$a], ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->privates['security.event_dispatcher.login_trainer'] ?? $container->load('getSecurity_EventDispatcher_LoginTrainerService')), 'login_trainer', ($container->privates['logger'] ?? self::getLoggerService($container)), true, true, []));
    }
}
