<?php

namespace ContainerITWHaqs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlimentoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AlimentoController' shared autowired service.
     *
     * @return \App\Controller\AlimentoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AlimentoController.php';

        $container->services['App\\Controller\\AlimentoController'] = $instance = new \App\Controller\AlimentoController(($container->privates['App\\Repository\\AlimentoRepository'] ?? $container->load('getAlimentoRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\AlimentoController', $container));

        return $instance;
    }
}
