<?php

namespace ContainerITWHaqs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleCheckerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Security\RoleChecker' shared autowired service.
     *
     * @return \App\Security\RoleChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Security/RoleChecker.php';

        return $container->services['App\\Security\\RoleChecker'] = new \App\Security\RoleChecker();
    }
}
