<?php

namespace Container8zYWUCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControlleruploadImageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l5xpj_O.App\Controller\BlogController::uploadImage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l5xpj_O.App\\Controller\\BlogController::uploadImage()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'slugger' => '?',
        ]))->withContext('App\\Controller\\BlogController::uploadImage()', $container);
    }
}
