<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCPBQlaO\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCPBQlaO/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCPBQlaO.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCPBQlaO\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerCPBQlaO\App_KernelProdContainer([
    'container.build_hash' => 'CPBQlaO',
    'container.build_id' => 'c3a09bca',
    'container.build_time' => 1769869671,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCPBQlaO');
