<?php

namespace ContainerCWGMhAu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioDietasControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UsuarioDietasController' shared autowired service.
     *
     * @return \App\Controller\UsuarioDietasController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/UsuarioDietasController.php';

        $container->services['App\\Controller\\UsuarioDietasController'] = $instance = new \App\Controller\UsuarioDietasController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\UsuarioDietasController', $container));

        return $instance;
    }
}
