<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BlogPost extends \App\Entity\BlogPost implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categoria' => [parent::class, 'categoria', null],
        "\0".parent::class."\0".'contenido' => [parent::class, 'contenido', null],
        "\0".parent::class."\0".'destacado' => [parent::class, 'destacado', null],
        "\0".parent::class."\0".'esPremium' => [parent::class, 'esPremium', null],
        "\0".parent::class."\0".'extracto' => [parent::class, 'extracto', null],
        "\0".parent::class."\0".'fechaActualizacion' => [parent::class, 'fechaActualizacion', null],
        "\0".parent::class."\0".'fechaCreacion' => [parent::class, 'fechaCreacion', null],
        "\0".parent::class."\0".'fechaPublicacion' => [parent::class, 'fechaPublicacion', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imagenPortada' => [parent::class, 'imagenPortada', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'titulo' => [parent::class, 'titulo', null],
        'categoria' => [parent::class, 'categoria', null],
        'contenido' => [parent::class, 'contenido', null],
        'destacado' => [parent::class, 'destacado', null],
        'esPremium' => [parent::class, 'esPremium', null],
        'extracto' => [parent::class, 'extracto', null],
        'fechaActualizacion' => [parent::class, 'fechaActualizacion', null],
        'fechaCreacion' => [parent::class, 'fechaCreacion', null],
        'fechaPublicacion' => [parent::class, 'fechaPublicacion', null],
        'id' => [parent::class, 'id', null],
        'imagenPortada' => [parent::class, 'imagenPortada', null],
        'slug' => [parent::class, 'slug', null],
        'titulo' => [parent::class, 'titulo', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
