<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Suscripcion extends \App\Entity\Suscripcion implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activa' => [parent::class, 'activa', null],
        "\0".parent::class."\0".'autoRenovacion' => [parent::class, 'autoRenovacion', null],
        "\0".parent::class."\0".'entrenadorAsignado' => [parent::class, 'entrenadorAsignado', null],
        "\0".parent::class."\0".'estado' => [parent::class, 'estado', null],
        "\0".parent::class."\0".'fechaCreacion' => [parent::class, 'fechaCreacion', null],
        "\0".parent::class."\0".'fechaFin' => [parent::class, 'fechaFin', null],
        "\0".parent::class."\0".'fechaInicio' => [parent::class, 'fechaInicio', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'precioMensual' => [parent::class, 'precioMensual', null],
        "\0".parent::class."\0".'usuario' => [parent::class, 'usuario', null],
        'activa' => [parent::class, 'activa', null],
        'autoRenovacion' => [parent::class, 'autoRenovacion', null],
        'entrenadorAsignado' => [parent::class, 'entrenadorAsignado', null],
        'estado' => [parent::class, 'estado', null],
        'fechaCreacion' => [parent::class, 'fechaCreacion', null],
        'fechaFin' => [parent::class, 'fechaFin', null],
        'fechaInicio' => [parent::class, 'fechaInicio', null],
        'id' => [parent::class, 'id', null],
        'precioMensual' => [parent::class, 'precioMensual', null],
        'usuario' => [parent::class, 'usuario', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
