<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Plato extends \App\Entity\Plato implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'caloriasTotales' => [parent::class, 'caloriasTotales', null],
        "\0".parent::class."\0".'carbohidratosTotales' => [parent::class, 'carbohidratosTotales', null],
        "\0".parent::class."\0".'creadorId' => [parent::class, 'creadorId', null],
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null],
        "\0".parent::class."\0".'dietaPlatos' => [parent::class, 'dietaPlatos', null],
        "\0".parent::class."\0".'dificultad' => [parent::class, 'dificultad', null],
        "\0".parent::class."\0".'esPublico' => [parent::class, 'esPublico', null],
        "\0".parent::class."\0".'fechaCreacion' => [parent::class, 'fechaCreacion', null],
        "\0".parent::class."\0".'grasasTotales' => [parent::class, 'grasasTotales', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imagenUrl' => [parent::class, 'imagenUrl', null],
        "\0".parent::class."\0".'ingredientes' => [parent::class, 'ingredientes', null],
        "\0".parent::class."\0".'instrucciones' => [parent::class, 'instrucciones', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'proteinasTotales' => [parent::class, 'proteinasTotales', null],
        "\0".parent::class."\0".'tiempoPreparacion' => [parent::class, 'tiempoPreparacion', null],
        "\0".parent::class."\0".'tipoComida' => [parent::class, 'tipoComida', null],
        "\0".parent::class."\0".'totalValoraciones' => [parent::class, 'totalValoraciones', null],
        "\0".parent::class."\0".'valoracionPromedio' => [parent::class, 'valoracionPromedio', null],
        'caloriasTotales' => [parent::class, 'caloriasTotales', null],
        'carbohidratosTotales' => [parent::class, 'carbohidratosTotales', null],
        'creadorId' => [parent::class, 'creadorId', null],
        'descripcion' => [parent::class, 'descripcion', null],
        'dietaPlatos' => [parent::class, 'dietaPlatos', null],
        'dificultad' => [parent::class, 'dificultad', null],
        'esPublico' => [parent::class, 'esPublico', null],
        'fechaCreacion' => [parent::class, 'fechaCreacion', null],
        'grasasTotales' => [parent::class, 'grasasTotales', null],
        'id' => [parent::class, 'id', null],
        'imagenUrl' => [parent::class, 'imagenUrl', null],
        'ingredientes' => [parent::class, 'ingredientes', null],
        'instrucciones' => [parent::class, 'instrucciones', null],
        'nombre' => [parent::class, 'nombre', null],
        'proteinasTotales' => [parent::class, 'proteinasTotales', null],
        'tiempoPreparacion' => [parent::class, 'tiempoPreparacion', null],
        'tipoComida' => [parent::class, 'tipoComida', null],
        'totalValoraciones' => [parent::class, 'totalValoraciones', null],
        'valoracionPromedio' => [parent::class, 'valoracionPromedio', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
