<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \App\Entity\Usuario implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'altura' => [parent::class, 'altura', null],
        "\0".parent::class."\0".'apellidos' => [parent::class, 'apellidos', null],
        "\0".parent::class."\0".'calendarios' => [parent::class, 'calendarios', null],
        "\0".parent::class."\0".'caloriasDiarias' => [parent::class, 'caloriasDiarias', null],
        "\0".parent::class."\0".'dietasAsignadas' => [parent::class, 'dietasAsignadas', null],
        "\0".parent::class."\0".'edad' => [parent::class, 'edad', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'entrenadorAsignado' => [parent::class, 'entrenadorAsignado', null],
        "\0".parent::class."\0".'entrenamientosAsignados' => [parent::class, 'entrenamientosAsignados', null],
        "\0".parent::class."\0".'entrenamientosCreados' => [parent::class, 'entrenamientosCreados', null],
        "\0".parent::class."\0".'esPremium' => [parent::class, 'esPremium', null],
        "\0".parent::class."\0".'fechaNacimiento' => [parent::class, 'fechaNacimiento', null],
        "\0".parent::class."\0".'fechaPremium' => [parent::class, 'fechaPremium', null],
        "\0".parent::class."\0".'fechaRegistro' => [parent::class, 'fechaRegistro', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imc' => [parent::class, 'imc', null],
        "\0".parent::class."\0".'nivelActividad' => [parent::class, 'nivelActividad', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'notasSalud' => [parent::class, 'notasSalud', null],
        "\0".parent::class."\0".'objetivo' => [parent::class, 'objetivo', null],
        "\0".parent::class."\0".'observaciones' => [parent::class, 'observaciones', null],
        "\0".parent::class."\0".'passwordHash' => [parent::class, 'passwordHash', null],
        "\0".parent::class."\0".'pesoActual' => [parent::class, 'pesoActual', null],
        "\0".parent::class."\0".'pesoObjetivo' => [parent::class, 'pesoObjetivo', null],
        "\0".parent::class."\0".'porcentajeGrasa' => [parent::class, 'porcentajeGrasa', null],
        "\0".parent::class."\0".'resetToken' => [parent::class, 'resetToken', null],
        "\0".parent::class."\0".'resetTokenExpires' => [parent::class, 'resetTokenExpires', null],
        "\0".parent::class."\0".'rol' => [parent::class, 'rol', null],
        "\0".parent::class."\0".'sexo' => [parent::class, 'sexo', null],
        "\0".parent::class."\0".'suscripciones' => [parent::class, 'suscripciones', null],
        "\0".parent::class."\0".'telefono' => [parent::class, 'telefono', null],
        "\0".parent::class."\0".'ultimaConexion' => [parent::class, 'ultimaConexion', null],
        'altura' => [parent::class, 'altura', null],
        'apellidos' => [parent::class, 'apellidos', null],
        'calendarios' => [parent::class, 'calendarios', null],
        'caloriasDiarias' => [parent::class, 'caloriasDiarias', null],
        'dietasAsignadas' => [parent::class, 'dietasAsignadas', null],
        'edad' => [parent::class, 'edad', null],
        'email' => [parent::class, 'email', null],
        'entrenadorAsignado' => [parent::class, 'entrenadorAsignado', null],
        'entrenamientosAsignados' => [parent::class, 'entrenamientosAsignados', null],
        'entrenamientosCreados' => [parent::class, 'entrenamientosCreados', null],
        'esPremium' => [parent::class, 'esPremium', null],
        'fechaNacimiento' => [parent::class, 'fechaNacimiento', null],
        'fechaPremium' => [parent::class, 'fechaPremium', null],
        'fechaRegistro' => [parent::class, 'fechaRegistro', null],
        'id' => [parent::class, 'id', null],
        'imc' => [parent::class, 'imc', null],
        'nivelActividad' => [parent::class, 'nivelActividad', null],
        'nombre' => [parent::class, 'nombre', null],
        'notasSalud' => [parent::class, 'notasSalud', null],
        'objetivo' => [parent::class, 'objetivo', null],
        'observaciones' => [parent::class, 'observaciones', null],
        'passwordHash' => [parent::class, 'passwordHash', null],
        'pesoActual' => [parent::class, 'pesoActual', null],
        'pesoObjetivo' => [parent::class, 'pesoObjetivo', null],
        'porcentajeGrasa' => [parent::class, 'porcentajeGrasa', null],
        'resetToken' => [parent::class, 'resetToken', null],
        'resetTokenExpires' => [parent::class, 'resetTokenExpires', null],
        'rol' => [parent::class, 'rol', null],
        'sexo' => [parent::class, 'sexo', null],
        'suscripciones' => [parent::class, 'suscripciones', null],
        'telefono' => [parent::class, 'telefono', null],
        'ultimaConexion' => [parent::class, 'ultimaConexion', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
