<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PlatoAlimento extends \App\Entity\PlatoAlimento implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'alimento' => [parent::class, 'alimento', null],
        "\0".parent::class."\0".'cantidadGramos' => [parent::class, 'cantidadGramos', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'orden' => [parent::class, 'orden', null],
        "\0".parent::class."\0".'plato' => [parent::class, 'plato', null],
        'alimento' => [parent::class, 'alimento', null],
        'cantidadGramos' => [parent::class, 'cantidadGramos', null],
        'id' => [parent::class, 'id', null],
        'orden' => [parent::class, 'orden', null],
        'plato' => [parent::class, 'plato', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
