<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DiaEjercicio extends \App\Entity\DiaEjercicio implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'descansoSegundos' => [parent::class, 'descansoSegundos', null],
        "\0".parent::class."\0".'diaEntrenamiento' => [parent::class, 'diaEntrenamiento', null],
        "\0".parent::class."\0".'ejercicio' => [parent::class, 'ejercicio', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'notas' => [parent::class, 'notas', null],
        "\0".parent::class."\0".'orden' => [parent::class, 'orden', null],
        "\0".parent::class."\0".'repeticiones' => [parent::class, 'repeticiones', null],
        "\0".parent::class."\0".'series' => [parent::class, 'series', null],
        'descansoSegundos' => [parent::class, 'descansoSegundos', null],
        'diaEntrenamiento' => [parent::class, 'diaEntrenamiento', null],
        'ejercicio' => [parent::class, 'ejercicio', null],
        'id' => [parent::class, 'id', null],
        'notas' => [parent::class, 'notas', null],
        'orden' => [parent::class, 'orden', null],
        'repeticiones' => [parent::class, 'repeticiones', null],
        'series' => [parent::class, 'series', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
