<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Alimento extends \App\Entity\Alimento implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'calorias' => [parent::class, 'calorias', null],
        "\0".parent::class."\0".'carbohidratos' => [parent::class, 'carbohidratos', null],
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null],
        "\0".parent::class."\0".'grasas' => [parent::class, 'grasas', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imagenUrl' => [parent::class, 'imagenUrl', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'precioKg' => [parent::class, 'precioKg', null],
        "\0".parent::class."\0".'proteinas' => [parent::class, 'proteinas', null],
        "\0".parent::class."\0".'tipoAlimento' => [parent::class, 'tipoAlimento', null],
        'calorias' => [parent::class, 'calorias', null],
        'carbohidratos' => [parent::class, 'carbohidratos', null],
        'descripcion' => [parent::class, 'descripcion', null],
        'grasas' => [parent::class, 'grasas', null],
        'id' => [parent::class, 'id', null],
        'imagenUrl' => [parent::class, 'imagenUrl', null],
        'nombre' => [parent::class, 'nombre', null],
        'precioKg' => [parent::class, 'precioKg', null],
        'proteinas' => [parent::class, 'proteinas', null],
        'tipoAlimento' => [parent::class, 'tipoAlimento', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
