<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HistorialPago extends \App\Entity\HistorialPago implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null],
        "\0".parent::class."\0".'estado' => [parent::class, 'estado', null],
        "\0".parent::class."\0".'fechaActualizacion' => [parent::class, 'fechaActualizacion', null],
        "\0".parent::class."\0".'fechaPago' => [parent::class, 'fechaPago', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'idTransaccionExterna' => [parent::class, 'idTransaccionExterna', null],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null],
        "\0".parent::class."\0".'metodoPago' => [parent::class, 'metodoPago', null],
        "\0".parent::class."\0".'moneda' => [parent::class, 'moneda', null],
        "\0".parent::class."\0".'monto' => [parent::class, 'monto', null],
        "\0".parent::class."\0".'suscripcion' => [parent::class, 'suscripcion', null],
        "\0".parent::class."\0".'usuario' => [parent::class, 'usuario', null],
        'descripcion' => [parent::class, 'descripcion', null],
        'estado' => [parent::class, 'estado', null],
        'fechaActualizacion' => [parent::class, 'fechaActualizacion', null],
        'fechaPago' => [parent::class, 'fechaPago', null],
        'id' => [parent::class, 'id', null],
        'idTransaccionExterna' => [parent::class, 'idTransaccionExterna', null],
        'metadata' => [parent::class, 'metadata', null],
        'metodoPago' => [parent::class, 'metodoPago', null],
        'moneda' => [parent::class, 'moneda', null],
        'monto' => [parent::class, 'monto', null],
        'suscripcion' => [parent::class, 'suscripcion', null],
        'usuario' => [parent::class, 'usuario', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
