<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ejercicio extends \App\Entity\Ejercicio implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null],
        "\0".parent::class."\0".'entrenamientoEjercicios' => [parent::class, 'entrenamientoEjercicios', null],
        "\0".parent::class."\0".'grupoMuscular' => [parent::class, 'grupoMuscular', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nivelDificultad' => [parent::class, 'nivelDificultad', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'tipo' => [parent::class, 'tipo', null],
        "\0".parent::class."\0".'totalValoraciones' => [parent::class, 'totalValoraciones', null],
        "\0".parent::class."\0".'valoracionPromedio' => [parent::class, 'valoracionPromedio', null],
        "\0".parent::class."\0".'videoUrl' => [parent::class, 'videoUrl', null],
        'descripcion' => [parent::class, 'descripcion', null],
        'entrenamientoEjercicios' => [parent::class, 'entrenamientoEjercicios', null],
        'grupoMuscular' => [parent::class, 'grupoMuscular', null],
        'id' => [parent::class, 'id', null],
        'nivelDificultad' => [parent::class, 'nivelDificultad', null],
        'nombre' => [parent::class, 'nombre', null],
        'tipo' => [parent::class, 'tipo', null],
        'totalValoraciones' => [parent::class, 'totalValoraciones', null],
        'valoracionPromedio' => [parent::class, 'valoracionPromedio', null],
        'videoUrl' => [parent::class, 'videoUrl', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
