<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dieta extends \App\Entity\Dieta implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'asignadoAUsuario' => [parent::class, 'asignadoAUsuario', null],
        "\0".parent::class."\0".'calendarios' => [parent::class, 'calendarios', null],
        "\0".parent::class."\0".'caloriasTotales' => [parent::class, 'caloriasTotales', null],
        "\0".parent::class."\0".'carbohidratosTotales' => [parent::class, 'carbohidratosTotales', null],
        "\0".parent::class."\0".'creador' => [parent::class, 'creador', null],
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null],
        "\0".parent::class."\0".'dietaPlatos' => [parent::class, 'dietaPlatos', null],
        "\0".parent::class."\0".'esPublica' => [parent::class, 'esPublica', null],
        "\0".parent::class."\0".'fechaCreacion' => [parent::class, 'fechaCreacion', null],
        "\0".parent::class."\0".'grasasTotales' => [parent::class, 'grasasTotales', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'proteinasTotales' => [parent::class, 'proteinasTotales', null],
        "\0".parent::class."\0".'totalValoraciones' => [parent::class, 'totalValoraciones', null],
        "\0".parent::class."\0".'valoracionPromedio' => [parent::class, 'valoracionPromedio', null],
        'asignadoAUsuario' => [parent::class, 'asignadoAUsuario', null],
        'calendarios' => [parent::class, 'calendarios', null],
        'caloriasTotales' => [parent::class, 'caloriasTotales', null],
        'carbohidratosTotales' => [parent::class, 'carbohidratosTotales', null],
        'creador' => [parent::class, 'creador', null],
        'descripcion' => [parent::class, 'descripcion', null],
        'dietaPlatos' => [parent::class, 'dietaPlatos', null],
        'esPublica' => [parent::class, 'esPublica', null],
        'fechaCreacion' => [parent::class, 'fechaCreacion', null],
        'grasasTotales' => [parent::class, 'grasasTotales', null],
        'id' => [parent::class, 'id', null],
        'nombre' => [parent::class, 'nombre', null],
        'proteinasTotales' => [parent::class, 'proteinasTotales', null],
        'totalValoraciones' => [parent::class, 'totalValoraciones', null],
        'valoracionPromedio' => [parent::class, 'valoracionPromedio', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
