<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Entrenador extends \App\Entity\Entrenador implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activo' => [parent::class, 'activo', null],
        "\0".parent::class."\0".'anosExperiencia' => [parent::class, 'anosExperiencia', null],
        "\0".parent::class."\0".'apellidos' => [parent::class, 'apellidos', null],
        "\0".parent::class."\0".'biografia' => [parent::class, 'biografia', null],
        "\0".parent::class."\0".'certificacion' => [parent::class, 'certificacion', null],
        "\0".parent::class."\0".'cvUrl' => [parent::class, 'cvUrl', null],
        "\0".parent::class."\0".'dietas' => [parent::class, 'dietas', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'entrenamientos' => [parent::class, 'entrenamientos', null],
        "\0".parent::class."\0".'especialidad' => [parent::class, 'especialidad', null],
        "\0".parent::class."\0".'estadoAplicacion' => [parent::class, 'estadoAplicacion', null],
        "\0".parent::class."\0".'fechaAplicacion' => [parent::class, 'fechaAplicacion', null],
        "\0".parent::class."\0".'fotoUrl' => [parent::class, 'fotoUrl', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'motivoRechazo' => [parent::class, 'motivoRechazo', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'passwordHash' => [parent::class, 'passwordHash', null],
        "\0".parent::class."\0".'precioSesionPresencial' => [parent::class, 'precioSesionPresencial', null],
        "\0".parent::class."\0".'telefono' => [parent::class, 'telefono', null],
        "\0".parent::class."\0".'totalValoraciones' => [parent::class, 'totalValoraciones', null],
        "\0".parent::class."\0".'valoracionPromedio' => [parent::class, 'valoracionPromedio', null],
        'activo' => [parent::class, 'activo', null],
        'anosExperiencia' => [parent::class, 'anosExperiencia', null],
        'apellidos' => [parent::class, 'apellidos', null],
        'biografia' => [parent::class, 'biografia', null],
        'certificacion' => [parent::class, 'certificacion', null],
        'cvUrl' => [parent::class, 'cvUrl', null],
        'dietas' => [parent::class, 'dietas', null],
        'email' => [parent::class, 'email', null],
        'entrenamientos' => [parent::class, 'entrenamientos', null],
        'especialidad' => [parent::class, 'especialidad', null],
        'estadoAplicacion' => [parent::class, 'estadoAplicacion', null],
        'fechaAplicacion' => [parent::class, 'fechaAplicacion', null],
        'fotoUrl' => [parent::class, 'fotoUrl', null],
        'id' => [parent::class, 'id', null],
        'motivoRechazo' => [parent::class, 'motivoRechazo', null],
        'nombre' => [parent::class, 'nombre', null],
        'passwordHash' => [parent::class, 'passwordHash', null],
        'precioSesionPresencial' => [parent::class, 'precioSesionPresencial', null],
        'telefono' => [parent::class, 'telefono', null],
        'totalValoraciones' => [parent::class, 'totalValoraciones', null],
        'valoracionPromedio' => [parent::class, 'valoracionPromedio', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
