<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CalendarioUsuario extends \App\Entity\CalendarioUsuario implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'completado' => [parent::class, 'completado', null],
        "\0".parent::class."\0".'diaSemana' => [parent::class, 'diaSemana', null],
        "\0".parent::class."\0".'dieta' => [parent::class, 'dieta', null],
        "\0".parent::class."\0".'entrenamiento' => [parent::class, 'entrenamiento', null],
        "\0".parent::class."\0".'fechaAsignacion' => [parent::class, 'fechaAsignacion', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'notas' => [parent::class, 'notas', null],
        "\0".parent::class."\0".'usuario' => [parent::class, 'usuario', null],
        'completado' => [parent::class, 'completado', null],
        'diaSemana' => [parent::class, 'diaSemana', null],
        'dieta' => [parent::class, 'dieta', null],
        'entrenamiento' => [parent::class, 'entrenamiento', null],
        'fechaAsignacion' => [parent::class, 'fechaAsignacion', null],
        'id' => [parent::class, 'id', null],
        'notas' => [parent::class, 'notas', null],
        'usuario' => [parent::class, 'usuario', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
