<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DiaEntrenamiento extends \App\Entity\DiaEntrenamiento implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'concepto' => [parent::class, 'concepto', null],
        "\0".parent::class."\0".'diaSemana' => [parent::class, 'diaSemana', null],
        "\0".parent::class."\0".'ejercicios' => [parent::class, 'ejercicios', null],
        "\0".parent::class."\0".'entrenamiento' => [parent::class, 'entrenamiento', null],
        "\0".parent::class."\0".'esDescanso' => [parent::class, 'esDescanso', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'orden' => [parent::class, 'orden', null],
        'concepto' => [parent::class, 'concepto', null],
        'diaSemana' => [parent::class, 'diaSemana', null],
        'ejercicios' => [parent::class, 'ejercicios', null],
        'entrenamiento' => [parent::class, 'entrenamiento', null],
        'esDescanso' => [parent::class, 'esDescanso', null],
        'id' => [parent::class, 'id', null],
        'orden' => [parent::class, 'orden', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
