<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Entrenamiento extends \App\Entity\Entrenamiento implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'asignadoAUsuario' => [parent::class, 'asignadoAUsuario', null],
        "\0".parent::class."\0".'calendarios' => [parent::class, 'calendarios', null],
        "\0".parent::class."\0".'creador' => [parent::class, 'creador', null],
        "\0".parent::class."\0".'creadorUsuario' => [parent::class, 'creadorUsuario', null],
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null],
        "\0".parent::class."\0".'dias' => [parent::class, 'dias', null],
        "\0".parent::class."\0".'duracionMinutos' => [parent::class, 'duracionMinutos', null],
        "\0".parent::class."\0".'entrenamientoEjercicios' => [parent::class, 'entrenamientoEjercicios', null],
        "\0".parent::class."\0".'esPublico' => [parent::class, 'esPublico', null],
        "\0".parent::class."\0".'fechaCreacion' => [parent::class, 'fechaCreacion', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nivelDificultad' => [parent::class, 'nivelDificultad', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'tipo' => [parent::class, 'tipo', null],
        "\0".parent::class."\0".'totalValoraciones' => [parent::class, 'totalValoraciones', null],
        "\0".parent::class."\0".'valoracionPromedio' => [parent::class, 'valoracionPromedio', null],
        'asignadoAUsuario' => [parent::class, 'asignadoAUsuario', null],
        'calendarios' => [parent::class, 'calendarios', null],
        'creador' => [parent::class, 'creador', null],
        'creadorUsuario' => [parent::class, 'creadorUsuario', null],
        'descripcion' => [parent::class, 'descripcion', null],
        'dias' => [parent::class, 'dias', null],
        'duracionMinutos' => [parent::class, 'duracionMinutos', null],
        'entrenamientoEjercicios' => [parent::class, 'entrenamientoEjercicios', null],
        'esPublico' => [parent::class, 'esPublico', null],
        'fechaCreacion' => [parent::class, 'fechaCreacion', null],
        'id' => [parent::class, 'id', null],
        'nivelDificultad' => [parent::class, 'nivelDificultad', null],
        'nombre' => [parent::class, 'nombre', null],
        'tipo' => [parent::class, 'tipo', null],
        'totalValoraciones' => [parent::class, 'totalValoraciones', null],
        'valoracionPromedio' => [parent::class, 'valoracionPromedio', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
