<?php

namespace ContainerASkLEZ6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrenamientoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EntrenamientoController' shared autowired service.
     *
     * @return \App\Controller\EntrenamientoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EntrenamientoController.php';

        $container->services['App\\Controller\\EntrenamientoController'] = $instance = new \App\Controller\EntrenamientoController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\EntrenamientoController', $container));

        return $instance;
    }
}
