<?php

namespace ContainerWCxsZc6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrenadorLoginSuccessHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Security\EntrenadorLoginSuccessHandler' shared autowired service.
     *
     * @return \App\Security\EntrenadorLoginSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'AuthenticationSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'EntrenadorLoginSuccessHandler.php';

        return $container->services['App\\Security\\EntrenadorLoginSuccessHandler'] = new \App\Security\EntrenadorLoginSuccessHandler(($container->privates['App\\Security\\EntrenadorLoginSuccessHandler.inner'] ?? $container->load('getEntrenadorLoginSuccessHandler_InnerService')), ($container->privates['App\\Repository\\EntrenadorRepository'] ?? $container->load('getEntrenadorRepositoryService')));
    }
}
